// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NMDJmOe97FSBeRz3FOg2k25wZh-eccs',
    appId: '1:598620125308:web:8d02b7e473c4af512031f9',
    messagingSenderId: '598620125308',
    projectId: 'musrenbang-bfcaa',
    authDomain: 'musrenbang-bfcaa.firebaseapp.com',
    storageBucket: 'musrenbang-bfcaa.firebasestorage.app',
    measurementId: 'G-L7NZY6NYPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkb0yyYzFJ-Q0v0OSgN6GBKUstn1ZydVI',
    appId: '1:598620125308:android:a4b8bd3b110b3f532031f9',
    messagingSenderId: '598620125308',
    projectId: 'musrenbang-bfcaa',
    storageBucket: 'musrenbang-bfcaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZ5ecLKP5DDpz60a3hsVIzhEth4--k3A',
    appId: '1:598620125308:ios:79ab818d21afd9132031f9',
    messagingSenderId: '598620125308',
    projectId: 'musrenbang-bfcaa',
    storageBucket: 'musrenbang-bfcaa.firebasestorage.app',
    iosBundleId: 'com.bily.musrenbang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZ5ecLKP5DDpz60a3hsVIzhEth4--k3A',
    appId: '1:598620125308:ios:79ab818d21afd9132031f9',
    messagingSenderId: '598620125308',
    projectId: 'musrenbang-bfcaa',
    storageBucket: 'musrenbang-bfcaa.firebasestorage.app',
    iosBundleId: 'com.bily.musrenbang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NMDJmOe97FSBeRz3FOg2k25wZh-eccs',
    appId: '1:598620125308:web:ed6030a034b8bd122031f9',
    messagingSenderId: '598620125308',
    projectId: 'musrenbang-bfcaa',
    authDomain: 'musrenbang-bfcaa.firebaseapp.com',
    storageBucket: 'musrenbang-bfcaa.firebasestorage.app',
    measurementId: 'G-SCSG5EGVVY',
  );
}
